### PR TITLE
Get keys regex

### PR DESCRIPTION
**Pull request by emdete**
rewrite of the parsing part of getting key bindings from cc files using regex

### CODE REVIEW

**Comment by gauteh** [comment]
thanks, this looks good, I think either:

- fix the " more:" to have a comma in front and only appear if there are
  aliases,
- or make new lines as you suggested.

**Comment by emdete** [comment]
done so. so all lines are comments now, all default keys at the end. so you can add / change stuff without loosing doc of the default

**Comment by gauteh** [comment]
M. Dietrich writes on February 24, 2016 19:49:
> done so. so all lines are comments now, all default keys at the end. so you can add / change stuff without loosing doc of the default

looks good, but I think it made more sense to have the default after the
'=' too. then it is easy to see what needs to be replaced, and you can
just uncomment and replace the key when you want to make a modification.

**Comment by emdete** [comment]
done.

**Comment by gauteh** [comment]
M. Dietrich writes on February 25, 2016 13:35:
> done.

Thanks, merged.

**Pull request closed without merging**
