### PR TITLE
remove "using namespace" from headers.

### PR DESCRIPTION
**Pull request by ff2000**
Also start cleaning up includes. The only "using" i left was for ptree in src/config.hh. I hope (and think) this won't do any damage. I could do something with that (namespace/type alias) if you want.

When there was an issue in a .cc-file I also tried to reduce pollution of global
namespace. Especially have a look at those. We can can come up with a general rule
(style guide) for those things, and I can fix that. Or you merge it and we fix
remaining style issues later.

(As a side effect I found a fix for #60)

### CODE REVIEW

**Comment by gauteh** [comment]
Great! I knew my bad habits would come back and bite me. I definitely want some coding style guidelines, I had some vague stuff in [Contributing](https://github.com/gauteh/astroid/wiki/Contributing). I would happily accepts suggestions, or just  go ahead and do it and then we can tweak it afterwards.

Other contributions and improvements are very much appreciated. Cleaner, and better structured, code is safer, less bug-prone, easier to work with and easier to contribute to.

(merged).

**Comment by gauteh** [comment]
In e.g.: theme.cc there is still a using boost::filesystem while there
is a using bfs::path further down, is this intentional?

**Comment by ff2000** [comment]
Excerpts from Gaute Hope's message of Januar 18, 2016 3:54 :
> In e.g.: theme.cc there is still a using boost::filesystem while there
> is a using bfs::path further down, is this intentional?
I think there are still plenty "using namespace" in implementation files
around. This one looks like I have missed.

I also would have liked to discuss some general rules what to allow and
what not.
I think it is also good to prevent `using namespace std` in the scope of
a translation unit. I also think most of the time it doesn't hurt to
type `std::`. If it gets tedious (like all those `endl`) IMHO pulling in
one name with `using std::endl` is OK.
In the tests I pulled in some symbols in the global namespace, I am not
so happy with that, but that are 'just' tests...

Boost is something special because of the long and nested namespace
names. IMHO aliasing is the best way to deal with that (even with a
semantic completion engine in place), and doing it in globally doesn't
hurt.

That's just my opinion. Astroid is your project and if you think this is
too pedantic I'm fine with it :) But if we really want to get some sort
of consistency it's better to know what to do, because otherwise the
mess AFTER style changes might be bigger than before ;)

**Comment by gauteh** [comment]
ff2000 writes on January 18, 2016 16:47:
> Excerpts from Gaute Hope's message of Januar 18, 2016 3:54 :
>> In e.g.: theme.cc there is still a using boost::filesystem while there
>> is a using bfs::path further down, is this intentional?
> I think there are still plenty "using namespace" in implementation files
> around. This one looks like I have missed.

Ok, just wondering if it fit into the style changes you were aiming for.
 
> I also would have liked to discuss some general rules what to allow and
> what not.

Definetely, if there are some stuff we could borrow that would be good.
If you have suggestions I would appreciate it, I am not a fan of making
it overly expressive though, that just makes the code a pain to write
and read. Having rules, and as soon as possible would be great!

> I think it is also good to prevent `using namespace std` in the scope of
> a translation unit. I also think most of the time it doesn't hurt to
> type `std::`. If it gets tedious (like all those `endl`) IMHO pulling in
> one name with `using std::endl` is OK.

Yup, agreed. I guess it is only std::endl that it would make sense to
pull in globally. Also, what do you think about putting `using
std::find_if` etc in the functions that need them, it feels tedious to
keep writing std:: for every single one.

As you probably noticed I got tired of writing Glib::ustring, this could
probably be done in a better way.

> In the tests I pulled in some symbols in the global namespace, I am not
> so happy with that, but that are 'just' tests...

:) fine by me.
 
> Boost is something special because of the long and nested namespace
> names. IMHO aliasing is the best way to deal with that (even with a
> semantic completion engine in place), and doing it in globally doesn't
> hurt.

Yeah, `namespace bfs = boost::filesystem;` and similar seems like a good
alternative. 
 
> That's just my opinion. Astroid is your project and if you think this is
> too pedantic I'm fine with it :) But if we really want to get some sort
> of consistency it's better to know what to do, because otherwise the
> mess AFTER style changes might be bigger than before ;)

Agreed. I am sure we can find a good balance. Also, I don't mind sharing
ownership with dedicated contributors. I do not feel particularily
possessive about my coding style, I defintely made some choices on the
pragmatic side of getting a working concept up and going. Please don't
hesitate to suggest changes to my style!

I quickly googled some stuff, but most existing style guildelines seem
very comprehensive (e.g.: http://www.stroustrup.com/JSF-AV-rules.pdf), I
don't expect anyone to read 141 pages before sending a patch to Astroid.

Regards, Gaute

**Pull request closed without merging**
