### PR TITLE
Licenses

### PR DESCRIPTION
**Pull request by hugoroy**

### CODE REVIEW

**Comment by gauteh** [comment]
Great!

Also, some stuff from ner was used, but it is GPLv3 so I guess it is
already covered? I see that the repository is offline now.

**Comment by hugoroy** [comment]
↪ janvier 9, 2016 5:18 , Gaute Hope:
> Great!
> 
> Also, some stuff from ner was used, but it is GPLv3 so I guess it is
> already covered? I see that the repository is offline now.

No, it isn't entirely covered. If parts of ner was adapted into astroid,
we need to comply with the terms (so we need to mention their copyright
and warranty notices).

**Comment by gauteh** [comment]
Ok, would you mind including it in this PR? I don't really know if much of the original code remains, as it had some bugs and I removed it. Anyway, attaching my latest copy of the ner code.
[ner-2013-01-23.zip](https://github.com/gauteh/astroid/files/84079/ner-2013-01-23.zip)

**Comment by hugoroy** [comment]
1. I suppose that there's nothing left from sup? 
2. How much of an adaption is it from ner?

I couldn't see much left of the original code but to be cautious I took into account that the license is GPL-3 only (not the 'or later' version). But that's for you to assess and decide.

**Comment by gauteh** [comment]
Hugo Roy writes on January 10, 2016 18:12:
> 1. I suppose that there's nothing left from sup? 

No. That's all in notmuch. The rest is GUI which is completely
different, except some inspiration.

> 2. How much of an adaption is it from ner?
> 
> I couldn't see much left of the original code but to be cautious I took into account that the license is GPL-3 only (not the 'or later' version). But that's for you to assess and decide.

It is not really an adaption. I have modified and used some minor chunks
of code, for instance the function that calls msmptp and sends an email.
With @micharlforney's permission, I guess it is alright as it is.

**Comment by michaelforney** [comment]
What's the question here?

If any of the ner code I authored is still left, I am happy to cooperate with any re-licensing you may want to do for astroid.

**Comment by hugoroy** [comment]
Relicensing to "gplv3 or any later version" as opposed to just version 3 would be nice to be consistent with @gauteh's license choice for astroid.

Then my question 2 above would be mostly moot.

**Comment by gauteh** [comment]
Merged!

**Comment by hugoroy** [comment]
@michaelforney @gauteh in reference to this https://github.com/gauteh/astroid/pull/44#issuecomment-170399700 it would be good to license astroid under GPLv3 or any later version :-)

**Comment by gauteh** [comment]
Isn't astroid already "GPLv3 or later"?

**Comment by hugoroy** [comment]
Currently, no, because of the parts of ner that's only GPLv3

**Comment by gauteh** [comment]
Ok, are you @michaelforney willing to relicence the parts of ner that I have used in astroid to "GPLv3 or any later version"?

**Comment by gauteh** [comment]
Hugo Roy writes on April 27, 2016 22:08:
> Currently, no, because of the parts of ner that's only GPLv3
> 

By the way, I am now including some parts of gmime that seems to be LGPL:

https://github.com/gauteh/astroid/blob/master/src/utils/gmime/gmime-filter-html-bq.c

**Comment by michaelforney** [comment]
I agree to relicense the parts of ner that are used in astroid under the terms of GPLv3 or any later version.

**Comment by gauteh** [comment]
@michaelforney: Thank you.

**Comment by hugoroy** [comment]
OK. I'll update the licensing info.
-- 
Envoyé de mon appareil mobile. 
Sent from my mobile device.

**Comment by hugoroy** [comment]
This can be merged @gauteh

**Comment by gauteh** [comment]
Hugo Roy writes on April 30, 2016 19:24:
> This can be merged @gauteh 
> 

Thanks, merged.

**Pull request closed without merging**
