### PR TITLE
[WIP] Refactor config access

### PR DESCRIPTION
**Pull request by ff2000**
This will come in handy for reading ~/.notmuch-config
without interfering astroid-config.

### CODE REVIEW

**Comment by ff2000** [comment]
As the title says - work in progress. So don't merge in this state.

**Comment by ff2000** [comment]
Reading and merging of ~/.notmuch-config should work now, at least concerning the current features.
Some commits can be squashed, but I think the one with reading and warning about deprecated values should be kept separate, so we can simply revert that change in case astroid reaches v0.7 (or whichever version will remove the config options).

I hope I will find the time tomorrow to add support for maildir.synchronize_flags.

**Comment by ff2000** [comment]
I now think renaming the keys to access notmuch-config is not really a good idea, because new contributors might get confused as they would expect other keys. Also debugging might get somewhat harder and bugs might slip in. [database.path instead of some config("astroid.notmuch").db]
I think I will also add a separate function "Astroid::notmuch_config()" to make things even more clear.
@gauteh Take your time and think about the changes as soon as you are AFAFK ;)

**Comment by ff2000** [comment]
@gauteh The last commit implements tag_to_maildirflags synchronization. If you want I can create another PR for that - I just wanted to see if everything comes together and fix #31 ;)

**Comment by ff2000** [comment]
What remains:
- Handling of deprecated values: Is it really needed? Or is it enough to tell the user in the release notes to set "astroid.notmuch_config" (or astroid.notmuch.config"?) and use that for db-path and excluded tags - and completely ignore the other notmuch-related settings in astroid-config?
- Can we remove "astroid.notmuch.[db, excluded_tags]" from default_config? I think we can and should.
- Should astroid.config.version be incremented?
- Should "astroid.notmuch.sent_tags" stay where it is? Now that Astroid::notmuch_config() is its own function I think it can. But I wondered if this could be placed in the AccountManager and give the user the possibility to tag sent messages depending on the account. That way one could automatically add a tag for "work" or "family" when using dedicated accounts.

(The last point again could be done in a seperate PR - it just popped up while digging through the code)

**Comment by gauteh** [comment]
I think this looks very promising! I will have to have a more through
look at the config access later, but I like the new approach. I agree
that notmuch_config should be accessed with a separate function (or at
least be clearly separable from the original config).

Some comment below:

ff2000 writes on January 25, 2016 9:24:
> What remains:
> - Handling of deprecated values: Is it really needed? Or is it enough to tell the user in the release notes to set "astroid.notmuch_config" (or astroid.notmuch.config"?) and use that for db-path and excluded tags - and completely ignore the other notmuch-related settings in astroid-config?

Yes, I don't think we need to be too careful about non-critical issues.

> - Can we remove "astroid.notmuch.[db, excluded_tags]" from default_config? I think we can and should.

Yes.

> - Should astroid.config.version be incremented?

Yes, at least for support issues (we can ask the user which version he
runs).

> - Should "astroid.notmuch.sent_tags" stay where it is? Now that Astroid::notmuch_config() is its own function I think it can. But I wondered if this could be placed in the AccountManager and give the user the possibility to tag sent messages depending on the account. That way one could automatically add a tag for "work" or "family" when using dedicated accounts.

I always thought that the .notmuch. sub-section was a bit out of place,
perhaps sent_tags should be under edit_message? Perhaps we can just
remove the whole notmuch section after adding notmuch_config()?

I added support for per-account sent-tags not long ago in #51 :)

**Comment by ff2000** [comment]
Excerpts from Gaute Hope's message of Januar 25, 2016 9:53 :
> I think this looks very promising! I will have to have a more through
> look at the config access later, but I like the new approach. I agree
> that notmuch_config should be accessed with a separate function (or at
> least be clearly separable from the original config).
> 
> Some comment below:
> 
> ff2000 writes on January 25, 2016 9:24:
>> What remains:
>> - Handling of deprecated values: Is it really needed? Or is it enough to tell the user in the release notes to set "astroid.notmuch_config" (or astroid.notmuch.config"?) and use that for db-path and excluded tags - and completely ignore the other notmuch-related settings in astroid-config?
> 
> Yes, I don't think we need to be too careful about non-critical issues.

Ok, (manually) reverted accessing those deprecated values

> 
>> - Can we remove "astroid.notmuch.[db, excluded_tags]" from default_config? I think we can and should.
> 
> Yes.

Done.

> 
>> - Should astroid.config.version be incremented?
> 
> Yes, at least for support issues (we can ask the user which version he
> runs).

Done, incremented to 3.

> 
>> - Should "astroid.notmuch.sent_tags" stay where it is? Now that Astroid::notmuch_config() is its own function I think it can. But I wondered if this could be placed in the AccountManager and give the user the possibility to tag sent messages depending on the account. That way one could automatically add a tag for "work" or "family" when using dedicated accounts.
> 
> I always thought that the .notmuch. sub-section was a bit out of place,
> perhaps sent_tags should be under edit_message? Perhaps we can just
> remove the whole notmuch section after adding notmuch_config()?

I did not do that, yet. There is a "mail" section that already
configures sending-preferences - mail.sent_tags sunds ok, too.
Probably a new section "account_defaults" would make sence? There we
could also store (fallback)defaults for sendmail, save_sent,
save_sent_to, save_drafts_to, so users like me wouldn' have to dupe
those settings for each account. ;)

But I'm fine with edit_message.sent_tags, too.

In any case we need to make sure that old settings get moved to the new
location - which should be doable with a small config_version_check.

> 
> I added support for per-account sent-tags not long ago in #51 :)

Thx, completely missed that :)

===

I did not yet squash any commits - Do you want to have several dedicated
commits? Or is it OK to squash it into one commit?

**Comment by gauteh** [comment]
ff2000 writes on January 27, 2016 10:55:
> [...]
>
> Done.

great!

>>> - Should "astroid.notmuch.sent_tags" stay where it is? Now that Astroid::notmuch_config() is its own function I think it can. But I wondered if this could be placed in the AccountManager and give the user the possibility to tag sent messages depending on the account. That way one could automatically add a tag for "work" or "family" when using dedicated accounts.
>>
>> I always thought that the .notmuch. sub-section was a bit out of place,
>> perhaps sent_tags should be under edit_message? Perhaps we can just
>> remove the whole notmuch section after adding notmuch_config()?
>
> I did not do that, yet. There is a "mail" section that already
> configures sending-preferences - mail.sent_tags sunds ok, too.
> Probably a new section "account_defaults" would make sence? There we
> could also store (fallback)defaults for sendmail, save_sent,
> save_sent_to, save_drafts_to, so users like me wouldn' have to dupe
> those settings for each account. ;)

I guess all of those could go in the 'mail' section too? However, I am a
little bit reluctant to add fallbacks like that. It is after all not
that much of a hassle to copy-paste your first account config. It feels
safer and less complicated to rather fail than fallback to something un-inteded.


> But I'm fine with edit_message.sent_tags, too.

'mail' makes more sense to me. then 'dryrun_sending' can go in there
too. agreed?

> In any case we need to make sure that old settings get moved to the new
> location - which should be doable with a small config_version_check.

Yes, I am afraid this will become a pain to maintain. But hopefully it
the config file will stabilize soon, let's make sure we get it right now
so that we don't end up with more checks.

> ===
>
> I did not yet squash any commits - Do you want to have several dedicated
> commits? Or is it OK to squash it into one commit?

Several dedicated commits is better! Once the branch matures we can fix
up the reverts and minor improvements and squash them a bit together.
You can do this and push --force if you want (once it is basically ready
for merging), or I can try to make sense of it before I merge.

**Comment by ff2000** [comment]
> I guess all of those could go in the 'mail' section too? However, I am a
> little bit reluctant to add fallbacks like that. It is after all not
> that much of a hassle to copy-paste your first account config. It feels
> safer and less complicated to rather fail than fallback to something un-inteded.

Agreed. Let's go the safe way and keep it as it is.

>> But I'm fine with edit_message.sent_tags, too.
> 
> 'mail' makes more sense to me. then 'dryrun_sending' can go in there
> too. agreed?

Agreed

>> In any case we need to make sure that old settings get moved to the new
>> location - which should be doable with a small config_version_check.
> 
> Yes, I am afraid this will become a pain to maintain. But hopefully it
> the config file will stabilize soon, let's make sure we get it right now
> so that we don't end up with more checks.

Could be done in a seperate function, so that future config version
changes can be migrated step-by-step to the most recent version.

> Several dedicated commits is better! Once the branch matures we can fix
> up the reverts and minor improvements and squash them a bit together.
> You can do this and push --force if you want (once it is basically ready
> for merging), or I can try to make sense of it before I merge.

Would be great if you could do that. I'm still not recovered and have a
hard time to even answer E-Mails (as you might have realised ;))

**Comment by gauteh** [comment]
ff2000 writes on January 29, 2016 9:59:
>>> In any case we need to make sure that old settings get moved to the new
>>> location - which should be doable with a small config_version_check.
>>
>> Yes, I am afraid this will become a pain to maintain. But hopefully it
>> the config file will stabilize soon, let's make sure we get it right now
>> so that we don't end up with more checks.
>
> Could be done in a seperate function, so that future config version
> changes can be migrated step-by-step to the most recent version.

I am sure you already noticed `[Config::check_config (...)](https://github.com/gauteh/astroid/blob/master/src/config.cc#L272)`.

>> Several dedicated commits is better! Once the branch matures we can fix
>> up the reverts and minor improvements and squash them a bit together.
>> You can do this and push --force if you want (once it is basically ready
>> for merging), or I can try to make sense of it before I merge.
>
> Would be great if you could do that. I'm still not recovered and have a
> hard time to even answer E-Mails (as you might have realised ;))

No worries, it's supposed to be fun. I am really busy the next days too.

**Comment by gauteh** [comment]
Gaute Hope writes on January 29, 2016 12:35:
> ff2000 writes on January 29, 2016 9:59:
>>>> In any case we need to make sure that old settings get moved to the new
>>>> location - which should be doable with a small config_version_check.
>>>
>>> Yes, I am afraid this will become a pain to maintain. But hopefully it
>>> the config file will stabilize soon, let's make sure we get it right now
>>> so that we don't end up with more checks.
>>
>> Could be done in a seperate function, so that future config version
>> changes can be migrated step-by-step to the most recent version.
> 
> I am sure you already noticed `[Config::check_config (...)](https://github.com/gauteh/astroid/blob/master/src/config.cc#L272)`.
> 
>>> Several dedicated commits is better! Once the branch matures we can fix
>>> up the reverts and minor improvements and squash them a bit together.
>>> You can do this and push --force if you want (once it is basically ready
>>> for merging), or I can try to make sense of it before I merge.
>>
>> Would be great if you could do that. I'm still not recovered and have a
>> hard time to even answer E-Mails (as you might have realised ;))
> 
> No worries, it's supposed to be fun. I am really busy the next days too.
> 
> 

You can check out my changes on:
https://github.com/gauteh/astroid/tree/refactor-config-gaute , in the
end I went back to warn about deprecation, but not fix it. I also found
a few things that you missed and rebased it to current master, let me
know if I have been using it wrongly. I was planning on squashing out
some of the commits that you seem to have discarded in later commits.

**Comment by gauteh** [comment]
As it is now, any error messages concerning the config is drowned in
everything else. Need to remove most of the debug output. Also, perhaps
make a script that looks for calls to `register_key` and `register_run`
to find keys and hooks without needing the user to scan through the
terminal output. I do not run astroid in the terminal, and it shouldn't
be necessary.

Perhaps a log window should be opened automatically every-time there is
an error? Or the output could be cached for a say 1000 lines or
something.

**Comment by ff2000** [comment]
But there aren't any specific errors this PR causes for you?

I also thought about that. Especially when there are warnings/errors at
startup. Don't know if it's overkill to make the LogLevel configurable,
so that pedantics could also get notified about Warnings? Would be
especially great if also the log window/console output could ignore
everything lower than MinimumLogLevel to minimize [ DEBUG ] spamming ;)
I think an ordinary user might not be interested always in DEBUG
messages. A cmdline-switch to overwrite config settings for debug
purposes would make sense, then. (--log-level=debug)

Concerning notification about errors:
There is that nice bar that pops up in the bottom of the window to query
for user input. Couldn't that be used?
`There were 12 warnings and 3 errors. Open log window? (yes no)`
IMHO would be more user friendly than just forcing focus on a different
mode...
Caching makes sense, but probably using a timer to notify the user would
be better?
And if the log window already is opened, one could set notify-state on
the tab and fade in an error/warning/... icon on the right side of the
tab bar (like when sending a message)

Excerpts from Gaute Hope's message of Januar 30, 2016 11:06 :

**Comment by gauteh** [comment]
ff2000 writes on January 30, 2016 12:26:
> But there aren't any specific errors this PR causes for you?
> 
> I also thought about that. Especially when there are warnings/errors at
> startup. Don't know if it's overkill to make the LogLevel configurable,
> so that pedantics could also get notified about Warnings? Would be
> especially great if also the log window/console output could ignore
> everything lower than MinimumLogLevel to minimize [ DEBUG ] spamming ;)
> I think an ordinary user might not be interested always in DEBUG
> messages. A cmdline-switch to overwrite config settings for debug
> purposes would make sense, then. (--log-level=debug)

Yes, both good!

> Concerning notification about errors:
> There is that nice bar that pops up in the bottom of the window to query
> for user input. Couldn't that be used?
> `There were 12 warnings and 3 errors. Open log window? (yes no)`
> IMHO would be more user friendly than just forcing focus on a different
> mode...
> Caching makes sense, but probably using a timer to notify the user would
> be better?
> And if the log window already is opened, one could set notify-state on
> the tab and fade in an error/warning/... icon on the right side of the
> tab bar (like when sending a message)

We could cache serious errors, or cache them untill the user opens a
window. Especially errors occuring before the mainwindow is opened needs
to be cached. Perhaps just a info bar, or icon, and then fade it out
after a little while (but not the icon untill the log view is opened). I
like it better if the user dont have to interact with the warning/error
and can just ignore it.

Could maybe put the wrong db path stuff in here too?

**Comment by gauteh** [comment]
ff2000 writes on January 30, 2016 12:26:
> But there aren't any specific errors this PR causes for you?

No, it seems to be working fine. Been running it (with my minor
modifications) for a litte while now.

**Comment by gauteh** [comment]
Merged. So users have to know about:

* astroid.notmuch_config points to the correct ~/.notmuch-config
* astroid.notmuch.exclude_tags must be updated in ~/.notmuch-config
  (implemented after last release).
* astroid.notmuch.sent_tags have been moved to astroid.mail.sent_tags

**Pull request closed without merging**
