### PR TITLE
#71: Print focused message

### LINKED ISSUE #71: Printing e-mails
Printing e-mails with `sup` was always a hassle. Have you any plans to render mails with HTML/CSS and make them easy to print directly from astroid? Or is this already supported?

### PR DESCRIPTION
**Pull request by gauteh**
Prints one message.

### CODE REVIEW

**Comment by gauteh** [comment]
Changed it to only printing the focused message, focused stuff is removed. Some stuff with the date remains.

**Comment by ff2000** [comment]
Excerpts from Gaute Hope's message of Januar 21, 2016 9:53 :
> Changed it to only printing the focused message, focused stuff is removed. Some stuff with the date remains.

What about C-P for printing the current message and C-S-P for printing
the whole thread?
Also it migt be great if attachments got printed, too. I just opened #73
for that.

**Comment by gauteh** [comment]
ff2000 writes on January 21, 2016 10:18:
> Excerpts from Gaute Hope's message of Januar 21, 2016 9:53 :
>> Changed it to only printing the focused message, focused stuff is removed. Some stuff with the date remains.
> 
> What about C-P for printing the current message and C-S-P for printing
> the whole thread?
> Also it migt be great if attachments got printed, too. I just opened #73
> for that.

C-S-P is the same as C-P (upper case). Note that C-p is already taken
for previous message (+ expand). Perhaps C-M-p for the thread?

**Comment by gauteh** [comment]
It would be great with a right-click context menu for thread-view too.

**Comment by gauteh** [comment]
Gaute Hope writes on January 21, 2016 10:22:
> ff2000 writes on January 21, 2016 10:18:
>> Excerpts from Gaute Hope's message of Januar 21, 2016 9:53 :
>>> Changed it to only printing the focused message, focused stuff is removed. Some stuff with the date remains.
>> 
>> What about C-P for printing the current message and C-S-P for printing
>> the whole thread?
>> Also it migt be great if attachments got printed, too. I just opened #73
>> for that.
> 
> C-S-P is the same as C-P (upper case). Note that C-p is already taken
> for previous message (+ expand). Perhaps C-M-p for the thread?

Actually, I think the best way to do this would be to:
- mark messages with 't'
- press '+'
- then 'p' to print all marked messages.

**Comment by gauteh** [comment]
Merged.

**Pull request closed without merging**
