### PR TITLE
New screenshots :-)

### PR DESCRIPTION
**Pull request by hugoroy**

### CODE REVIEW

**Comment by ff2000** [comment]
Thread view screenshot could showcase a "real" threaded message (different levels) Flat is boring :P

**Comment by gauteh** [comment]
Nice, thanks! Maybe we should have an emacs-screenshot as well? Another
thing: should we go for standard locale (export LC_ALL=C)?

**Comment by hugoroy** [comment]
↪ avril 27, 2016 3:43 — Gaute Hope:
> Nice, thanks! Maybe we should have an emacs-screenshot as well? Another
> thing: should we go for standard locale (export LC_ALL=C)?


Here you go :-)

**Comment by hugoroy** [comment]
↪ avril 27, 2016 3:43 — Gaute Hope:
> thing: should we go for standard locale (export LC_ALL=C)?

I don't know about that :)

It's true that at the moment, the interface for me is a mix of French
and English. I do not mind that much, but it's true that some
consistency with the user's environment would be best.

**Comment by gauteh** [comment]
Hugo Roy writes on April 27, 2016 15:47:
> ↪ avril 27, 2016 3:43 — Gaute Hope:
>> thing: should we go for standard locale (export LC_ALL=C)?
> 
> I don't know about that :)
> 
> It's true that at the moment, the interface for me is a mix of French
> and English. I do not mind that much, but it's true that some
> consistency with the user's environment would be best.

I meant only in the screenshots, ideally all of astroid should be
localized.

**Comment by hugoroy** [comment]
Flat is now the default config.
-- 
Envoyé de mon appareil mobile. 
Sent from my mobile device.

**Comment by hugoroy** [comment]
Ha. I understand. How can i do that?
-- 
Envoyé de mon appareil mobile. 
Sent from my mobile device.

**Comment by gauteh** [comment]
Hugo Roy writes on April 27, 2016 15:53:
> Ha. I understand. How can i do that?

```
$ export LC_ALL=C
$ astroid
```

**Comment by hugoroy** [comment]
↪ avril 27, 2016 3:57 — Gaute Hope:
> Hugo Roy writes on April 27, 2016 15:53:
>> Ha. I understand. How can i do that?
> 
> ```
> $ export LC_ALL=C
> $ astroid
> ```
> 

I got this:

[debug] (15:59:52): pm: add pane
[info ] (15:59:52): db: open db read-only, waiting for lock..
[debug] (15:59:52): db: read-only got lock.
[debug] (15:59:52): db: open time: 0.552 ms.
[debug] (15:59:52): ql: refresh stats..
[debug] (15:59:52): mw: does not have focus, will not grab modal.
[debug] (15:59:52): mw: does not have focus, will not grab modal.
terminate called after throwing an instance of 'Glib::ConvertError'
[1]    13479 abort (core dumped)  ./astroid

**Comment by gauteh** [comment]
Hugo Roy writes on April 27, 2016 16:00:
> ↪ avril 27, 2016 3:57 — Gaute Hope:
>> Hugo Roy writes on April 27, 2016 15:53:
>>> Ha. I understand. How can i do that?
>> 
>> ```
>> $ export LC_ALL=C
>> $ astroid
>> ```
>> 
> 
> I got this:
> 
> [debug] (15:59:52): pm: add pane
> [info ] (15:59:52): db: open db read-only, waiting for lock..
> [debug] (15:59:52): db: read-only got lock.
> [debug] (15:59:52): db: open time: 0.552 ms.
> [debug] (15:59:52): ql: refresh stats..
> [debug] (15:59:52): mw: does not have focus, will not grab modal.
> [debug] (15:59:52): mw: does not have focus, will not grab modal.
> terminate called after throwing an instance of 'Glib::ConvertError'
> [1]    13479 abort (core dumped)  ./astroid
> 

Right, so it turns out we need an UTF-8 locale. Try: LC_ALL=en_US.utf-8

**Comment by hugoroy** [comment]
↪ avril 27, 2016 4:35 — Gaute Hope:
> Right, so it turns out we need an UTF-8 locale. Try: LC_ALL=en_US.utf-8


I got the same error message.

**Comment by gauteh** [comment]
Can you post the complete log and command that you used?

**Comment by hugoroy** [comment]
↪ avril 27, 2016 5:14 — Hugo Roy:
> ↪ avril 27, 2016 4:47 — Gaute Hope:
>> Can you post the complete log and command that you used?
>> 

    hugo@xps ~ % cd ~/.email/astroid 
    hugo@xps ~/.email/astroid (git)-[master] % export LC_ALL=en_US.utf-8
    hugo@xps ~/.email/astroid (git)-[master] % ./astroid 
    [info ] (17:13:53): welcome to astroid! - v0.4-388-g96f85aa0
    [debug] (17:13:53): utf8: 0, ANSI_X3.4-1968
    [debug] (17:13:53): loading gtk..

    (process:15440): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.
    [warn ] (17:13:53): astroid: instance already running, opening new window..
    hugo@xps ~/.email/astroid (git)-[master] % ./astroid 
    [info ] (17:14:32): welcome to astroid! - v0.4-388-g96f85aa0
    [debug] (17:14:32): utf8: 0, ANSI_X3.4-1968
    [debug] (17:14:32): loading gtk..

    (process:15490): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.
    [debug] (17:14:32): HOME: /home/hugo
    [info ] (17:14:32): cf: loading: "/home/hugo/.config/astroid/config"
    [info ] (17:14:32): cf: version: 5
    [ERROR] (17:14:32): config: option 'astroid.notmuch.db' is deprecated, it is read from notmuch config.
    [ERROR] (17:14:32): config: option 'astroid.notmuch.excluded_tags' is deprecated, it is read from notmuch config.
    [ERROR] (17:14:32): config: option 'astroid.notmuch.sent_tags' is deprecated, it is moved to 'mail.sent_tags'.
    [warn ] (17:14:32): editor.gvim.cmd and editor.gvim.args are replaced by editor.cmd, and may be removed.
    [info ] (17:14:32): notmuch db: /home/hugo/Mail
    [info ] (17:14:32): date: init.
    [info ] (17:14:32): keybindings: loading user bindings from: /home/hugo/.config/astroid/keybindings
    [debug] (17:14:32): ky: parsing line: main_window.close_page=C-w
    [debug] (17:14:32): ky: parsing line: thread_index.close_pane=C-w
    [debug] (17:14:32): ky: parsing line: main_window.search=/
    [debug] (17:14:32): ky: parsing line: main_window.next_page=l
    [debug] (17:14:32): ky: parsing line: main_window.previous_page=h
    [debug] (17:14:32): ky: parsing line: thread_index.multi=;
    [debug] (17:14:32): ky: parsing line: thread_index.label=+
    [debug] (17:14:32): ky: parsing line: thread_index.spam=X
    [debug] (17:14:32): ky: parsing run-hook: thread_index.run(/home/hugo/.config/astroid/hooks/toggle waiting %1)=w
    [debug] (17:14:32): ky: run: thread_index.run(w): /home/hugo/.config/astroid/hooks/toggle waiting %1
    [debug] (17:14:32): ky: parsing line: thread_view.next_message=j
    [debug] (17:14:32): ky: parsing line: thread_view.previous_message=k
    [debug] (17:14:32): ky: parsing line: thread_view.down=n
    [debug] (17:14:32): ky: parsing line: thread_view.up=p
    [debug] (17:14:32): ky: parsing line: thread_view.tag_message=+
    [info ] (17:14:32): ac: initializing accounts..
    [info ] (17:14:32): ac: setup account: tosdr for Hugo Roy (default: 0)
    [info ] (17:14:32): ac: setup account: fsfe for Hugo Roy (default: 0)
    [info ] (17:14:32): ac: setup account: avocat for Hugo Roy (default: 0)
    [info ] (17:14:32): ac: setup account: hugo for Hugo Roy (default: 1)
    [info ] (17:14:32): global actions: set up.
    [info ] (17:14:32): poll: setting up.
    [debug] (17:14:32): poll: interval: 800
    [debug] (17:14:32): poll: requested..
    [warn ] (17:14:32): astroid: starting a new window..
    [info ] (17:14:32): poll: polling: /home/hugo/.config/astroid/poll.sh
    [info ] (17:14:32): db: open db read-only, waiting for lock..
    [debug] (17:14:32): db: read-only got lock.
    [debug] (17:14:32): db: open time: 0.813 ms.
    [debug] (17:14:32): poll: revision before poll: 857706
    [info ] (17:14:32): db: closing db.
    [debug] (17:14:32): db: ro: waiting for lock to close..
    [debug] (17:14:32): db: ro: closing..
    [info ] (17:14:32): db: open db read-only, waiting for lock..
    [debug] (17:14:32): db: read-only got lock.
    [debug] (17:14:32): db: open time: 0.222 ms.
    [info ] (17:14:32): db: loaded 131 tags.
    [info ] (17:14:32): db: closing db.
    [debug] (17:14:32): db: ro: waiting for lock to close..
    [debug] (17:14:32): db: ro: closing..
    [debug] (17:14:32): mw: init, id: 1
    [info ] (17:14:32): astroid: got query: inbox: tag:inbox
    [info ] (17:14:32): re: using user configured resource: /home/hugo/.email/astroid/ui/no-mail.png
    [info ] (17:14:32): ky: run, binding: thread_index.run(w) (userdefined: 1) to: /home/hugo/.config/astroid/hooks/toggle waiting %1
    [debug] (17:14:32): pm: add pane
    [info ] (17:14:32): db: open db read-only, waiting for lock..
    [debug] (17:14:32): db: read-only got lock.
    [debug] (17:14:32): db: open time: 0.601 ms.
    [debug] (17:14:32): ql: refresh stats..
    [debug] (17:14:32): mw: does not have focus, will not grab modal.
    [debug] (17:14:32): mw: does not have focus, will not grab modal.
    terminate called after throwing an instance of 'Glib::ConvertError'
    [1]    15490 abort (core dumped)  ./astroid
    134 hugo@xps ~/.email/astroid (git)-[master] %                                                                                                                                              :(

**Comment by gauteh** [comment]
Seems like en_US.utf-8 is not enabled, you have to do that inlocale
settings, check Arch wiki. Probably need to reinstall glib afterwards.

Den onsdag 27. april 2016 skrev Hugo Roy <notifications@github.com>
følgende:

**Comment by hugoroy** [comment]
New screenshots!

**Comment by gauteh** [comment]
Thanks - but I don't really see any difference :) The dates are still
not in en_US.UTF-8 locale. Normally LC_ALL should fix that (but you can
check with the locale command). Otherwise, setting LC_TIME=en_US.UTF-8
should help.

**Comment by hugoroy** [comment]
Hm. Strange. I probably copied the wrong file because I had the right dates on the screen. This should be good now.

**Comment by gauteh** [comment]
Hugo Roy writes on April 27, 2016 18:00:
> Hm. Strange. I probably copied the wrong file because I had the right dates on the screen. This should be good now.
> 

Thanks, merged. One thing: The thread-view screenshot is unproportional
to the others, and it looks kind of weird now. I don't think it is
necessary with all that gray background.

**Comment by gauteh** [comment]
Will put emacs screenshot in wiki.

**Pull request closed without merging**
