### PR TITLE
Sent tag configurable

### PR DESCRIPTION
**Pull request by gauteh**

### CODE REVIEW

**Comment by hugoroy** [comment]
It works!

**Comment by gauteh** [comment]
Cool, did you test the per-account tags aswell?

Den søndag 10. januar 2016 skrev Hugo Roy <notifications@github.com>
følgende:

**Comment by hugoroy** [comment]
↪ janvier 10, 2016 7:57 , Gaute Hope:
> Cool, did you test the per-account tags aswell?

Yes, and it works

**Comment by hugoroy** [comment]
↪ janvier 10, 2016 8:28 , Hugo Roy:
> ↪ janvier 10, 2016 7:57 , Gaute Hope:
>> Cool, did you test the per-account tags aswell?
> 
> Yes, and it works
> 

Sorry, it doesn't work it seems.

For instance, I added this under one account:

            "save_sent": "true",
            "sent_tags": "sent,inbox,perso",

But only the sent_tags define in the main config options was taken into
account it seems.

**Comment by hugoroy** [comment]
↪ janvier 10, 2016 8:28 , Hugo Roy:
> ↪ janvier 10, 2016 7:57 , Gaute Hope:
>> Cool, did you test the per-account tags aswell?
> 
> Yes, and it works
> 

Actually, I'm mistaken. It does not seem to take the "sent_tags" defined
under one account.

**Comment by gauteh** [comment]
Hm, it should be, under the account:
```
"additional_sent_tags" : "perso"
```

if for instance you already got, globally:
```
"sent_tags" : "sent,inbox",
```

**Comment by hugoroy** [comment]
↪ janvier 10, 2016 9:45 , Gaute Hope:
> Hm, it should be, under the account:
> ```
> "additional_sent_tags" : "perso"
> ```

OK. I'm testing (will edit the github page).

It seems a bit over-the-top to me to have a separate name for the config
option.

**Comment by gauteh** [comment]
Hugo Roy writes on January 10, 2016 22:07:
> ↪ janvier 10, 2016 9:45 , Gaute Hope:
>> Hm, it should be, under the account:
>> ```
>> "additional_sent_tags" : "perso"
>> ```
> 
> OK. I'm testing (will edit the github page).
> 
> It seems a bit over-the-top to me to have a separate name for the config
> option.

It needs to be in the config section, and I wanted to make it clear that
it does not replace the global ones but add to them.

**Comment by gauteh** [comment]
Hm, it works here, are you sure you put the "additional_sent_tags" under
the account, like this:

```
        "gaute": {
            "name": "Gaute Hope",
            "email": "eg@gaute.vetsj.com",
            "gpgkey": "",
            "sendmail": "msmtp -a gaute.vetsj.com -t",
            "default": "true",
            "save_sent": "false",
            "save_sent_to": "",
            "save_drafts_to": "\/home\/gaute\/.mail\/drafts\/",
            "additional_sent_tags": "perso"
        },
```

**Comment by hugoroy** [comment]
↪ janvier 10, 2016 10:41 , Gaute Hope:
> Hm, it works here, are you sure you put the "additional_sent_tags" under
> the account, like this:

Yes, that's what I did. But I notice that now the field is empty.

**Comment by hugoroy** [comment]
↪ janvier 12, 2016 12:00 , Hugo Roy:
> ↪ janvier 10, 2016 10:41 , Gaute Hope:
>> Hm, it works here, are you sure you put the "additional_sent_tags" under
>> the account, like this:
> 
> Yes, that's what I did. But I notice that now the field is empty.
> 

And now it seems to work; I'm puzzled :)

**Comment by gauteh** [comment]
Hm, might have been some confusion around the configuration version, anyway I merged it :)

**Pull request closed without merging**
