### PR TITLE
ti: C-s cycle through sort order for thread_index, default is configurable

### PR DESCRIPTION
**Pull request by gauteh**
#45

### CODE REVIEW

**Comment by hugoroy** [comment]
The keybinding works, however "oldest" does not seem to work as expected:
capture d ecran de 2016-01-10 12-58-58

**Comment by gauteh** [comment]
It cycles through "oldest", "newest", "messageid", "unsorted". The default is newest so the one afterwards is messageid. Just check the log output.

**Comment by gauteh** [comment]
(what font are you using btw?)

**Comment by hugoroy** [comment]
Yes, I could see that. But when "oldest" is used, I can't really point out what is going on. The screenshot is an "oldest" sorting where a quite recent email was between two threads where there were no emails since yesterday.

(the font is http://input.fontbureau.com/ but it's not under a free license unfortunately -- just fine for personal use)

**Comment by gauteh** [comment]
Are you configuring through the config file or using C-s?

**Comment by gauteh** [comment]
I think this is because it is using the oldest message in the thread. Not the newest message, and then sort by thread. Not sure if it is possible to do it otherwise. It does look a bit weird in the thread-index. Could you check if there is an older message in the 5m thread?

**Comment by hugoroy** [comment]
Yes, it appears that it's sorting by oldest thread. Actually, this is logical. I guess that what mutt is doing for instance is sorting by email and not by thread. 

I think it's good enough :-) there's no point in trying to replicate how it would work in email-based mua like mutt.

**Pull request merged**
