### PR TITLE
Signatures: Included per-account signatures

### PR DESCRIPTION
**Pull request by gauteh**
Signatures can be either inlined or attached.

Unsure if I got the mail-attachement spec correct (if there is any).

#115.

### CODE REVIEW

**Comment by hugoroy** [comment]
It works well :+1: 

One thing is when an account has the signature set as default, then the signature does not appear instantly, but only after actually sending the message.

**Comment by gauteh** [comment]
Hugo Roy writes on April 25, 2016 0:04:
> It works well :+1: 
> 
> One thing is when an account has the signature set as default, then the signature does not appear instantly, but only after actually sending the message.
> 

Do you mean in the editor? It is not supposed to ever end up there. Do
you have the message as attachment or inline? Would you mind sending me
the relevant config-lines? On my part it is previewed the first time as
well (after just :wq<enter>).

**Comment by hugoroy** [comment]
I'll make a video :-)

I'm at work without my personal laptop but tonight I should.

Le 25 avril 2016 10:17:34 GMT+02:00, Gaute Hope <notifications@github.com> a écrit :
>Hugo Roy writes on April 25, 2016 0:04:
>> It works well :+1: 
>> 
>> One thing is when an account has the signature set as default, then
>the signature does not appear instantly, but only after actually
>sending the message.
>> 
>
>Do you mean in the editor? It is not supposed to ever end up there. Do
>you have the message as attachment or inline? Would you mind sending me
>the relevant config-lines? On my part it is previewed the first time as
>well (after just :wq<enter>).
>
>
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/gauteh/astroid/pull/117#issuecomment-214200916

-- 
Envoyé de mon appareil mobile. 
Sent from my mobile device.

**Comment by gauteh** [comment]
Aight!

Hugo Roy writes on April 25, 2016 10:27:
> I'll make a video :-)
> 
> I'm at work without my personal laptop but tonight I should.
-- 
err...

**Comment by hugoroy** [comment]
Switching to an email account with the singuature on by default (inline, not attached) does not seem to work in the editing window (or I have to move the mouse around for it to appear:
https://storage.5apps.com/hugo/public/shares/160426-1738-Capture%20d%27%C3%A9cran%20vid%C3%A9o%20de%2026-04-2016%2019%3A37%3A21.webm

**Comment by hugoroy** [comment]
Switching to an account where signatures are ON seems to turn it on for all accounts even when switching to one where signature are OFF by default
https://storage.5apps.com/hugo/public/shares/160426-1740-Capture%20d%27%C3%A9cran%20vid%C3%A9o%20de%2026-04-2016%2019%3A39%3A57.webm

**Comment by gauteh** [comment]
Hugo Roy writes on April 26, 2016 19:40:
> Switching to an account where signatures are ON seems to turn it on for all accounts even when switching to one where signature are OFF by default
> https://storage.5apps.com/hugo/public/shares/160426-1740-Capture%20d%27%C3%A9cran%20vid%C3%A9o%20de%2026-04-2016%2019%3A39%3A57.webm
> 

I was using some GTK signals wrongly, please try again!

**Comment by hugoroy** [comment]
↪ avril 27, 2016 8:42  — Gaute Hope:
> I was using some GTK signals wrongly, please try again!

Yep, seems all good :)

**Comment by gauteh** [comment]
Hugo Roy writes on April 27, 2016 9:06:
> ↪ avril 27, 2016 8:42  — Gaute Hope:
>> I was using some GTK signals wrongly, please try again!
> 
> Yep, seems all good :)

Merged. Thanks for testing and catching this.

(should do a new release soon).

-g

**Comment by hugoroy** [comment]
Awesome! :-)


-- 
Envoyé de mon appareil mobile. 
Sent from my mobile device.

**Pull request closed without merging**
